# Generated by Django 5.2.4 on 2025-07-11 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Current_balance',
            new_name='CurrentBalance',
        ),
    ]
