# Generated by Django 5.2.4 on 2025-07-11 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_current_balance_currentbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinghistory',
            name='current_balance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.currentbalance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trackinghistory',
            name='amount',
            field=models.FloatField(),
        ),
    ]
